# Generated by Django 4.1.4 on 2023-01-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('team_one_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_white', to='player.country')),
                ('team_two_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_black', to='player.country')),
            ],
            options={
                'verbose_name_plural': 'Match',
            },
        ),
    ]
