# Generated by Django 4.1.4 on 2022-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
