# Generated by Django 4.1.4 on 2022-12-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='New York', max_length=245),
        ),
    ]
