# Generated by Django 4.1.4 on 2022-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='nickename',
            field=models.CharField(default='Lemon', max_length=50),
        ),
    ]
