# Generated by Django 4.1.4 on 2022-12-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='is_default',
        ),
    ]
