# Generated by Django 4.1.4 on 2022-12-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address_nickename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='nickename',
            new_name='nickname',
        ),
    ]
